plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md


logo: logo2.jpg
description: [] 
title: Analysis of High-Dimensional Data
theme: jekyll-theme-minimal
