title: Analysis of High-Dimensional Data
logo: logo2.jpg
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - _exercises_and_solutions.md

theme: jekyll-theme-minimal
